### ISSUE TITLE
Valid Return Code on Errors

### ISSUE THREAD

**Issue by ARizzo35** [mkiiskila/mynewt_serial_uploader#2]
Hello, I don't currently have write access, but the current code does not return proper error codes on failures. I've added a small patch file below. It would be nice to get this merged in for use in automated tests.

```diff --git a/serial_upload.c b/serial_upload.c
index e1d9dd0..0bcfdf6 100755
--- a/serial_upload.c
+++ b/serial_upload.c
@@ -506,6 +506,7 @@ main(int argc, char **argv)
 {
     HANDLE fd;
     int rc;
+    int ret = EXIT_SUCCESS;

     cmdname = argv[0];
     state.imgchunk = 512;
@@ -535,9 +536,13 @@ main(int argc, char **argv)
     rc = echo_ctl(0);
     if (rc == 0) {
         rc = img_upload();
+    } else {
+        ret = EXIT_FAILURE;
     }
     if (rc == 0) {
         rc = reset_device();
+    } else {
+        ret = EXIT_FAILURE;
     }
 #if 0
     if (echo_ctl(1)) {
@@ -547,5 +552,5 @@ main(int argc, char **argv)
     free(state.file);
     fflush(stderr);
     fflush(stdout);
-    return 0;
+    return ret;
 }

**Comment by mkiiskila** [comment]
Thanks for submitting a fix.

However, your patch is not against the latest code in this repository. The return code should've been set properly since Jan 29.
See https://github.com/mkiiskila/mynewt_serial_uploader/commit/f9294d5a2b2e02a3ed6967c5d0fe118a52e350af

**Comment by ARizzo35** [comment]
Thanks. Have some other changes I would like to get into the code for better POSIX portability. Will open a new request.
